before:
  hooks:
    - go mod download
builds:
  - id: "oauth2t"
    main: "./cmd/oauth2t/main.go"
    binary: "oauth2t"
    goos:
      - linux
      - darwin
      - windows      
    env:
      - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - name: "oauth2t"
    url_template: "https://github.com/Contrast-Security-Inc/oauth2t/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@contrastsecurity.com
    tap:
      owner: "Contrast-Security-Inc"
      name: "homebrew-brew"
    folder: "Formula"
    skip_upload: false
    homepage: "https://github.com/Contrast-Security-Inc/oauth2t"
    description: "Access Token helper for OAuth2 comms."


